name: Update Repository

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # 00:00 UTC on the first day of every month

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for BFG to work on full history

      - name: Configure git
        run: |
          git config user.email "${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com"
          git config user.name "${{ github.repository_owner }}"

      - name: Detect upstream repository
        id: upstream
        run: |
          parent=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }} \
            | jq -r '.parent.full_name')

          if [ "$parent" = "null" ]; then
            echo "This repository is not a fork"
            exit 0
          fi

          echo "parent=$parent" >> $GITHUB_OUTPUT

      - name: Replace with upstream branch
        if: steps.upstream.outputs.parent != ''
        run: |
          git remote add upstream https://github.com/${{ steps.upstream.outputs.parent }}.git
          git fetch upstream
          DEFAULT_BRANCH=$(git remote show upstream | sed -n '/HEAD branch/s/.*: //p')
          git checkout -b imported-branch upstream/$DEFAULT_BRANCH
          git remote remove upstream
          git branch -M main
          git push origin main --force
